export const PETITION_STARTED = 'PETITION_STARTED';
export const PETITION_REQUESTED = 'PETITION_REQUESTED';
export const PETITION_SIGNED = 'PETITION_SIGNED';
export const PETITION_ERROR = 'PETITION_ERROR';